use crate::plot::colors::ColorTheme;
use crate::plot::core::PlotType;
use iced::Color;

#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum Message {
	UpdateHover(Option<String>),
	ChangePlotType(PlotType),
	SetMaxLegendRows(u32),
	SetLegendX(f32),
	SetLegendY(f32),
	SetXRotation(f32),
	SetXOffset(f32),
	ChangeColorTheme(ColorTheme),
	ChangeBackgroundColor(Color),
	ChangeBackgroundHex(String),
	ChangeDecorationColor(Color),
	ChangeDecorationHex(String),
	SetXMin(Option<f64>),
	SetXMax(Option<f64>),
	SetYMin(Option<f64>),
	SetYMax(Option<f64>),
	SetTitle(Option<String>),
	SetSubtitle(Option<String>),
	SetXLabel(Option<String>),
	SetYLabel(Option<String>),
	SetTitleOffset(f32),
	SetSubtitleOffset(f32),
	SetXLabelPadding(f32),
	SetYLabelPadding(f32),
	SetPlotPaddingTop(f32),
	SetPlotPaddingBottom(f32),
	SetPlotPaddingLeft(f32),
	SetPlotPaddingRight(f32),
	SetTitleSize(f32),
	SetSubtitleSize(f32),
	SetXLabelSize(f32),
	SetYLabelSize(f32),
	SetXTickSize(f32),
	SetYTickSize(f32),
	SetLegendSize(f32),
	SetXTicks(u32),
	SetYTicks(u32),
	ToggleSettings,
	CloseSettings,
}
